"""Storage provider protocol — shared by local, cloud, and future adapters."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StorageProvider(Protocol):
    """Abstract interface for invoice document persistence."""

    name: str

    # Businesses
    def load_businesses(self) -> dict[str, Any]: ...
    def save_businesses(self, businesses: dict[str, Any]) -> None: ...

    # Customers
    def load_customers(self) -> dict[str, Any]: ...
    def save_customers(self, customers: dict[str, Any]) -> None: ...

    # Invoices
    def load_invoices(self) -> dict[str, Any]: ...
    def load_active_invoices(self) -> dict[str, Any]: ...
    def save_invoices(self, invoices: dict[str, Any]) -> None: ...
    def get_invoice(self, number: int | str, *, include_deleted: bool = False) -> dict | None: ...
    def add_invoice(self, record: dict[str, Any]) -> None: ...
    def update_invoice_status(self, number: int | str, status: str) -> bool: ...
    def soft_delete_invoice(self, number: int | str) -> bool: ...

    # Settings (subset used by invoicing)
    def load_settings(self) -> dict[str, Any]: ...
    def save_settings(self, settings: dict[str, Any]) -> None: ...

    # PDF
    def get_pdf_dir(self) -> str: ...
    def pdf_available(self, number: int | str) -> bool: ...

    # Sync (cloud / offline queue)
    def has_pending_sync(self) -> bool: ...
    def flush_sync_queue(self) -> dict[str, Any]: ...
